---
- name: Test ansible.cfg
  hosts: all
  tasks:
    - name: Afficher le chemin du fichier de configuration utilise
      ansible.builtin.debug:
        msg: "{{ lookup('env','ANSIBLE_CONFIG') }}"
- hosts: all
  tasks:
    - name: Vérifier le fichier ansible.cfg chargé
      command: ansible --version
      register: ansible_ver

    - debug:
        var: ansible_ver.stdout_lines